# roles por defecto
NOMBRE_ROL_CLIENTE = "Cliente"
NOMBRE_ROL_GESTOR_DE_NEGOCIOS = "Gestor de Negocios"
NOMBRE_ROL_ADMINISTRADOR_DE_NEGOCIOS = "Administrador de Negocios"
NOMBRE_ROL_PROPIETARIO = "Propietario de Negocios"
NOMBRE_ROL_GESTOR_GENERAL_DE_NEGOCIOS = "Gestor General de Negocios"
NOMBRE_ROL_GESTOR_EVENTOS = "Gestor Eventos"
NOMBRE_ROL_DESARROLLADOR = "Desarrollador"
NOMBRE_ROL_VALIDADOR_DE_NEGOCIOS = "Validador de negocios"
NOMBRE_ROL_ADMINISTRADOR_DEL_SISTEMA = "Administrador del sistema"
NOMBRE_ROL_SUPER_USUARIO = "Super Usuario"

ID_ROL_CLIENTE = 1
ID_ROL_GESTOR_DE_NEGOCIOS = 3
ID_ROL_ADMINISTRADOR_DE_NEGOCIOS = 5
ID_ROL_PROPIETARIO = 2
ID_ROL_GESTOR_GENERAL_DE_NEGOCIOS = 6
ID_ROL_GESTOR_EVENTOS = 4
ID_ROL_DESARROLLADOR = 7
ID_ROL_VALIDADOR_DE_NEGOCIOS = 8
ID_ROL_ADMINISTRADOR_DEL_SISTEMA = 9
ID_ROL_SUPER_USUARIO = 10


NOMBRE_ROLES = [
    NOMBRE_ROL_CLIENTE,
    NOMBRE_ROL_GESTOR_DE_NEGOCIOS,
    NOMBRE_ROL_ADMINISTRADOR_DE_NEGOCIOS,
    NOMBRE_ROL_PROPIETARIO,
    NOMBRE_ROL_GESTOR_GENERAL_DE_NEGOCIOS,
    NOMBRE_ROL_GESTOR_EVENTOS,
    NOMBRE_ROL_DESARROLLADOR,
    NOMBRE_ROL_VALIDADOR_DE_NEGOCIOS,
    NOMBRE_ROL_ADMINISTRADOR_DEL_SISTEMA,
    NOMBRE_ROL_SUPER_USUARIO,
]
