# Generated by Django 4.2.7 on 2025-02-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_cliente', models.CharField(max_length=255, verbose_name='Nombre del cliente: ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='EquipamientoDelLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_equipo', models.CharField(max_length=255, verbose_name='Nombre del equipo: ')),
                ('fabricante_del_equipo', models.CharField(max_length=255, verbose_name='Fabricante del equipo: ')),
                ('descripicion_del_equipo', models.CharField(max_length=255, verbose_name='Descripción del equipo: ')),
                ('estado_del_equipo', models.CharField(choices=[('Roto', 'Roto'), ('En uso', 'En uso')], max_length=255, verbose_name='Estado en que se encuentra el equipo: ')),
                ('fecha_de_entrada_del_equipo_al_laboratorio', models.DateField(verbose_name='Fecha de entrada del equipo: ')),
                ('calibracion_del_equipo', models.FloatField(verbose_name='Calibración del equipo: ')),
            ],
            options={
                'verbose_name': 'Equipamientos',
                'verbose_name_plural': 'Equipamientos',
            },
        ),
        migrations.CreateModel(
            name='PrepararSoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_preparacion_de_la_solucion', models.DateField(verbose_name='Fecha de preaparación de la Solución: ')),
            ],
            options={
                'verbose_name': 'Preparar solución',
                'verbose_name_plural': 'Preparar soluciones',
            },
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_reactivo', models.CharField(max_length=255, verbose_name='Nombre del reactivo: ')),
                ('cantidad_de_reactivo', models.FloatField(verbose_name='Cantidad de reactivo: ')),
            ],
            options={
                'verbose_name': 'Reactivo',
                'verbose_name_plural': 'Reactivos',
            },
        ),
        migrations.CreateModel(
            name='SolucionesPreparadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_de_la_solucion_preparada', models.CharField(max_length=255, verbose_name='Identidicador de la solución preparada: ')),
                ('nombre_de_la_solucion_preparada', models.CharField(max_length=255, verbose_name='Nombre de la solución preparada: ')),
                ('cantidad_de_la_solucion_preparada', models.FloatField(verbose_name='Cantidad de solución preparada: ')),
            ],
            options={
                'verbose_name': 'Solución preparada',
                'verbose_name_plural': 'Soluciones preparadas',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_trabajador', models.CharField(max_length=255, verbose_name='Nombre del trabajador: ')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Soluciones_Preparadas_Producidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_soluciones_preparada_producidas', models.FloatField(verbose_name='Cantidad de solución preparada ya producida: ')),
                ('preparar_soluciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.prepararsoluciones', verbose_name='Preparar soluciones')),
                ('soluciones_preparadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.solucionespreparadas', verbose_name='Soluciones preparadas')),
            ],
            options={
                'verbose_name': 'Solución prep. producida',
                'verbose_name_plural': 'Soluciones preparadas producidas',
            },
        ),
        migrations.CreateModel(
            name='RegistroDeOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_del_registro_de_operacion', models.CharField(max_length=255, verbose_name='Identidicador del registro de operación: ')),
                ('fecha_de_registro_de_operacion', models.DateField(verbose_name='Fecha del registro de operación: ')),
                ('descripicion_del_registro_de_operacion', models.CharField(max_length=255, verbose_name='Descripción del registro de operación: ')),
                ('trabajador', models.ManyToManyField(to='project.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de operación',
                'verbose_name_plural': 'Registro de operaciones',
            },
        ),
        migrations.CreateModel(
            name='Reactivo_Consumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_reactivo_consumida', models.FloatField(verbose_name='Cantidad de reactivo consumida: ')),
                ('preparar_soluciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.prepararsoluciones', verbose_name='Preparar soluciones')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.reactivo', verbose_name='Reactivo')),
            ],
            options={
                'verbose_name': 'Reactivo consumido',
                'verbose_name_plural': 'Reactivos consumidos',
            },
        ),
        migrations.AddField(
            model_name='prepararsoluciones',
            name='registro_de_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.registrodeoperacion', verbose_name='Registro de operacion'),
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_de_la_muestra', models.CharField(max_length=255, verbose_name='Identidicador de la muestra: ')),
                ('nombre_de_la_muestra', models.CharField(max_length=255, verbose_name='Nombre de la muestra: ')),
                ('cantidad_de_la_muestra', models.FloatField(verbose_name='Cantidad de muestra: ')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cliente', verbose_name='Cliente')),
                ('reagistro_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.registrodeoperacion', verbose_name='Registro de operacion')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
            },
        ),
        migrations.CreateModel(
            name='EntradaDeReactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_entrada_del_reactivo', models.DateField(verbose_name='Fecha de entrada del reactivo: ')),
                ('cantidad_de_reactivo', models.FloatField(verbose_name='Cantidad de reactivo: ')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.reactivo', verbose_name='Reactivo')),
            ],
            options={
                'verbose_name': 'Entrada de reactivo',
                'verbose_name_plural': 'Entrada de reactivos',
            },
        ),
    ]
