# Generated by Django 4.2.7 on 2025-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactivo_consumido',
            name='preparar_soluciones',
        ),
        migrations.AddField(
            model_name='prepararsoluciones',
            name='reactivo_consumido',
            field=models.ManyToManyField(to='project.reactivo_consumido', verbose_name='Preparar soluciones'),
        ),
    ]
