# Generated by Django 4.2.7 on 2025-02-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamientodellaboratorio',
            name='identificador_del_equipo',
            field=models.CharField(default='', max_length=255, verbose_name='Identidicador del equipo: '),
            preserve_default=False,
        ),
    ]
