# Generated by Django 4.2.7 on 2025-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_reactivo_consumido_preparar_soluciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soluciones_preparadas_producidas',
            name='preparar_soluciones',
        ),
        migrations.AddField(
            model_name='soluciones_preparadas_producidas',
            name='preparar_soluciones',
            field=models.ManyToManyField(to='project.prepararsoluciones', verbose_name='???'),
        ),
    ]
