# Generated by Django 4.2.7 on 2025-02-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_equipamientodellaboratorio_identificador_del_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeterminacionDeLaGravedadEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(verbose_name='Temperatura:')),
                ('gravedad_especifica_resultante', models.FloatField(verbose_name='Grav. Específica Result:')),
                ('resultado_en_grado_API', models.FloatField(verbose_name='Gado API:')),
            ],
            options={
                'verbose_name': 'Det. Gravedad Especifica',
                'verbose_name_plural': 'Det. Gravedades Especificas',
            },
        ),
        migrations.CreateModel(
            name='DeterminacionDeLaTemperaturaDeCalentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_resultante', models.FloatField(verbose_name='Temperatura Result:')),
                ('viscosidad_resultante', models.FloatField(verbose_name='Viscosidad Result:')),
            ],
            options={
                'verbose_name': 'Det. Temp de Calentamiento',
                'verbose_name_plural': 'Det. Temps de Calentamiento',
            },
        ),
        migrations.CreateModel(
            name='DeterminacionDeLaViscosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viscosidad', models.FloatField(verbose_name='Viscosidad Result:')),
                ('tiempo_de_inicio', models.DateField(verbose_name='Tiempo Inicio:')),
                ('tiempo_de_final', models.DateField(verbose_name='Tiempo Final:')),
            ],
            options={
                'verbose_name': 'Det. Viscosidad',
                'verbose_name_plural': 'Det. Viscosidades',
            },
        ),
        migrations.CreateModel(
            name='DeterminacionDelValorCaloricoSuperior_Algoritmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calorico_superior_resultante', models.FloatField(verbose_name='Valor Calórico Result:')),
                ('gravedad_especifica_del_combustible', models.FloatField(verbose_name='Gravedad Específica:')),
                ('porcentaje_de_agua', models.FloatField(verbose_name='Porcentaje de Agua:')),
            ],
            options={
                'verbose_name': 'Det. Valor Calórico Sup. Algor',
                'verbose_name_plural': 'Det. Valores Calóricos Sup Algor',
            },
        ),
        migrations.CreateModel(
            name='DeterminacionDelValorCaloricoSuperior_Calorimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_introducida', models.FloatField(verbose_name='Temp. Introducida:')),
                ('valor_calorico_superior_resultante', models.FloatField(verbose_name='Valor Calórico Result:')),
                ('porciento_de_asufre_resultante', models.FloatField(verbose_name='% de Asufre Result:')),
                ('porciento_de_hidrogeno_resultante', models.FloatField(verbose_name='% de Hidrógeno Result:')),
                ('porciento_de_carbono_resultante', models.FloatField(verbose_name='% de Carbono Result:')),
            ],
            options={
                'verbose_name': 'Det. Valor Calórico Sup Calorím',
                'verbose_name_plural': 'Det. Valores Calóricos Sup Calorím',
            },
        ),
        migrations.CreateModel(
            name='LibroDeRegistroDeOperacione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo:')),
            ],
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='reagistro_operacion',
        ),
        migrations.RemoveField(
            model_name='prepararsoluciones',
            name='registro_de_operacion',
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='muestra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.muestra', verbose_name='Muestra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='preparar_soluciones',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.prepararsoluciones', verbose_name='Preparar Soluciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradadereactivo',
            name='cantidad_de_reactivo',
            field=models.FloatField(verbose_name='Cantidad de reactivo:'),
        ),
        migrations.AlterField(
            model_name='entradadereactivo',
            name='fecha_de_entrada_del_reactivo',
            field=models.DateField(verbose_name='Fecha de entrada:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='calibracion_del_equipo',
            field=models.FloatField(verbose_name='Calibración:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='descripicion_del_equipo',
            field=models.CharField(max_length=255, verbose_name='Descripción del equipo:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='estado_del_equipo',
            field=models.CharField(choices=[('Roto', 'Roto'), ('En uso', 'En uso')], max_length=255, verbose_name='Estado del equipo:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='fabricante_del_equipo',
            field=models.CharField(max_length=255, verbose_name='Fabricante:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='fecha_de_entrada_del_equipo_al_laboratorio',
            field=models.DateField(verbose_name='Fecha de entrada:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='identificador_del_equipo',
            field=models.CharField(max_length=255, verbose_name='Identidicador:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='nombre_del_equipo',
            field=models.CharField(max_length=255, verbose_name='Nombre: '),
        ),
        migrations.AlterField(
            model_name='prepararsoluciones',
            name='fecha_de_preparacion_de_la_solucion',
            field=models.DateField(verbose_name='Fecha de Prep. de la Sol.:'),
        ),
        migrations.AlterField(
            model_name='reactivo',
            name='cantidad_de_reactivo',
            field=models.FloatField(verbose_name='Cantidad de reactivo:'),
        ),
        migrations.AlterField(
            model_name='reactivo',
            name='nombre_del_reactivo',
            field=models.CharField(max_length=255, verbose_name='Nombre del reactivo:'),
        ),
        migrations.AlterField(
            model_name='reactivo_consumido',
            name='cantidad_de_reactivo_consumida',
            field=models.FloatField(verbose_name='Cantidad de React. Consumida:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='descripicion_del_registro_de_operacion',
            field=models.CharField(max_length=255, verbose_name='Descripción del registro:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='fecha_de_registro_de_operacion',
            field=models.DateField(verbose_name='Fecha del registro:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='identificador_del_registro_de_operacion',
            field=models.CharField(max_length=255, verbose_name='Identidicador:'),
        ),
        migrations.AlterField(
            model_name='soluciones_preparadas_producidas',
            name='cantidad_de_soluciones_preparada_producidas',
            field=models.FloatField(verbose_name='Cantidad Sol. Prep. Producida:'),
        ),
        migrations.AlterField(
            model_name='solucionespreparadas',
            name='cantidad_de_la_solucion_preparada',
            field=models.FloatField(verbose_name='Cantidad de Sol. Prep:'),
        ),
        migrations.AlterField(
            model_name='solucionespreparadas',
            name='identificador_de_la_solucion_preparada',
            field=models.CharField(max_length=255, verbose_name='Identidicador:'),
        ),
        migrations.AlterField(
            model_name='solucionespreparadas',
            name='nombre_de_la_solucion_preparada',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Sol. Prep:'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre_del_trabajador',
            field=models.CharField(max_length=255, verbose_name='Nombre del trabajador:'),
        ),
        migrations.CreateModel(
            name='DeterminacionDelValorCaloricoSuperior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_roto', models.BooleanField(default=False, verbose_name='Está Roto el Calorímetro')),
                ('determinacion_del_valor_calorico_superior_Algoritmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.determinaciondelvalorcaloricosuperior_algoritmo', verbose_name='Valor Calórico Sup. Medeiante el Algorítmo')),
                ('determinacion_del_valor_calorico_superior_Calorimetro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.determinaciondelvalorcaloricosuperior_calorimetro', verbose_name='Valor Calórico Sup. en el Calorímetro')),
            ],
            options={
                'verbose_name': 'Det. Valor Calórico Sup',
                'verbose_name_plural': 'Det. Valores Calóricos Sup',
            },
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='determinacion_de_la_gravedad_especifica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.determinaciondelagravedadespecifica', verbose_name='Det. Gravedad Especifica:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='determinacion_de_la_temperatura_de_calentamiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.determinaciondelatemperaturadecalentamiento', verbose_name='Det. Temp de Calentamiento:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='determinacion_de_la_viscosidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.determinaciondelaviscosidad', verbose_name='Det. Viscosidad:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='determinacion_del_valor_calorico_superior',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.determinaciondelvalorcaloricosuperior', verbose_name='Det. Valor Calórico Sup:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodeoperacion',
            name='libroDeRegistroDeOperacione',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.libroderegistrodeoperacione', verbose_name='Libro de Registro de Operacione'),
            preserve_default=False,
        ),
    ]
