# Generated by Django 4.2.7 on 2025-03-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_soluciones_preparadas_producidas_preparar_soluciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soluciones_preparadas_producidas',
            name='preparar_soluciones',
        ),
        migrations.AddField(
            model_name='prepararsoluciones',
            name='soluciones_preparadas_producidas',
            field=models.ManyToManyField(to='project.soluciones_preparadas_producidas', verbose_name='???'),
        ),
    ]
