# Generated by Django 4.2.7 on 2025-02-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_determinaciondelagravedadespecifica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determinaciondelvalorcaloricosuperior',
            name='determinacion_del_valor_calorico_superior_Algoritmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.determinaciondelvalorcaloricosuperior_algoritmo', verbose_name='Valor Calórico Sup. Medeiante el Algorítmo'),
        ),
        migrations.AlterField(
            model_name='determinaciondelvalorcaloricosuperior',
            name='determinacion_del_valor_calorico_superior_Calorimetro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.determinaciondelvalorcaloricosuperior_calorimetro', verbose_name='Valor Calórico Sup. en el Calorímetro'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='determinacion_de_la_gravedad_especifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.determinaciondelagravedadespecifica', verbose_name='Det. Gravedad Especifica:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='determinacion_de_la_temperatura_de_calentamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.determinaciondelatemperaturadecalentamiento', verbose_name='Det. Temp de Calentamiento:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='determinacion_de_la_viscosidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.determinaciondelaviscosidad', verbose_name='Det. Viscosidad:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='determinacion_del_valor_calorico_superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.determinaciondelvalorcaloricosuperior', verbose_name='Det. Valor Calórico Sup:'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.muestra', verbose_name='Muestra'),
        ),
        migrations.AlterField(
            model_name='registrodeoperacion',
            name='preparar_soluciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.prepararsoluciones', verbose_name='Preparar Soluciones'),
        ),
    ]
