# Generated by Django 4.2.7 on 2025-03-28 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_soluciones_preparadas_producidas_preparar_soluciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactivo',
            name='descripicion',
        ),
        migrations.AddField(
            model_name='reactivo',
            name='descripicion_del_reactivo',
            field=models.TextField(default='', verbose_name='Descripción del reactivo:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ensayodelcombustible',
            name='result_determinacion_de_la_gravedad_especifica',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Resultado de la gravedad específica'),
        ),
        migrations.AlterField(
            model_name='ensayodelcombustible',
            name='result_determinacion_de_la_temperatura_de_calentamiento',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Resultado de la Temp. de calentamiento'),
        ),
        migrations.AlterField(
            model_name='ensayodelcombustible',
            name='result_determinacion_de_la_viscosidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Resultado de la viscosidad'),
        ),
        migrations.AlterField(
            model_name='ensayodelcombustible',
            name='result_determinacion_del_valor_calorico',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Resultado del valor calórico'),
        ),
        migrations.AlterField(
            model_name='entradadereactivo',
            name='cantidad_de_reactivo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad de reactivo:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='calibracion_del_equipo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Calibración:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='descripicion_del_equipo',
            field=models.TextField(verbose_name='Descripción del equipo:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='identificador_del_equipo',
            field=models.CharField(max_length=255, unique=True, verbose_name='Identidicador:'),
        ),
        migrations.AlterField(
            model_name='equipamientodellaboratorio',
            name='nombre_del_equipo',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre del equipo no puede contener carateres especiales', regex='^[a-zA-Z0-9_ ]+$')], verbose_name='Nombre: '),
        ),
        migrations.AlterField(
            model_name='reactivo',
            name='cantidad_de_disponible',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad de reactivo:'),
        ),
        migrations.AlterField(
            model_name='reactivo_consumido',
            name='cantidad_de_reactivo_consumida',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad de React. Consumida:'),
        ),
        migrations.AlterField(
            model_name='soluciones_preparadas_producidas',
            name='cantidad_de_soluciones_preparada_producidas',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad Sol. Prep. Producida:'),
        ),
        migrations.AlterField(
            model_name='solucionespreparadas',
            name='cantidad_de_la_solucion_preparada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad de Sol. Prep:'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='ci',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El carné de identidad debe contener exactamente 11 números', regex='^\\d{11}$')], verbose_name='Carné de identidad:'),
        ),
    ]
