# Generated by Django 4.2.7 on 2025-03-28 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_trabajador_nombre_del_trabajador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='libroDeInforme',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rol_del_trabajador',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ ]+$')], verbose_name='Ocupación o cargo: '),
        ),
        migrations.DeleteModel(
            name='LibroDeInforme',
        ),
    ]
