# Generated by Django 4.2.7 on 2025-03-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_informe_librodeinforme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soluciones_preparadas_producidas',
            options={'verbose_name': 'Solución preparada producida', 'verbose_name_plural': 'Soluciones preparadas producidas'},
        ),
        migrations.RemoveField(
            model_name='ensayoaguavapor',
            name='preparar_soluciones',
        ),
        migrations.AlterField(
            model_name='ensayodelcombustible',
            name='preparar_soluciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.prepararsoluciones', verbose_name='Soluciones preparadas'),
        ),
        migrations.AlterField(
            model_name='prepararsoluciones',
            name='reactivo_consumido',
            field=models.ManyToManyField(to='project.reactivo_consumido', verbose_name='Reactivo consumido'),
        ),
        migrations.AlterField(
            model_name='prepararsoluciones',
            name='soluciones_preparadas_producidas',
            field=models.ManyToManyField(to='project.soluciones_preparadas_producidas', verbose_name='Soluciones preparadas producidas'),
        ),
        migrations.AddField(
            model_name='ensayoaguavapor',
            name='preparar_soluciones',
            field=models.ManyToManyField(to='project.prepararsoluciones', verbose_name='Soluciones preparadas para este ensaayo'),
        ),
    ]
