# Generated by Django 4.2.7 on 2025-03-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_soluciones_preparadas_producidas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayoaguavapor',
            name='descripicion_del_ensayo',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del ensayo'),
        ),
        migrations.AlterField(
            model_name='ensayodelcombustible',
            name='descripicion_del_resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del resultado'),
        ),
        migrations.RemoveField(
            model_name='ensayodelcombustible',
            name='preparar_soluciones',
        ),
        migrations.AddField(
            model_name='ensayodelcombustible',
            name='preparar_soluciones',
            field=models.ManyToManyField(to='project.prepararsoluciones', verbose_name='Soluciones preparadas para este ensaayo'),
        ),
    ]
