# Generated by Django 4.2.7 on 2025-03-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_ensayoaguavapor_descripicion_del_ensayo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='descripicion_del_informe',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del informe'),
        ),
        migrations.RemoveField(
            model_name='informe',
            name='preparar_soluciones',
        ),
        migrations.AddField(
            model_name='informe',
            name='preparar_soluciones',
            field=models.ManyToManyField(to='project.prepararsoluciones', verbose_name='Soluciones preparadas para este ensaayo'),
        ),
    ]
