# Generated by Django 4.2.7 on 2025-03-28 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_informe_descripicion_del_informe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamientodellaboratorio',
            options={'verbose_name': 'Equipamiento del laboratorio', 'verbose_name_plural': 'Equipamientos del laboratorio'},
        ),
        migrations.AddField(
            model_name='equipamientodellaboratorio',
            name='cantidad_actual',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad actual:'),
        ),
    ]
